In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [2]:
mlab_path = "/Users/priyankaramachandran/Desktop/UCD Courses/CN Project/dataset/MLab Sacramento.csv"

mlab = pd.read_csv(mlab_path)
mlab.head()

,id,date,test_uuid,test_time,throughput_mbps,min_rtt_ms,loss_rate,client_city,client_state,postal_code,client_latitude,client_longitude,isp,asn,rn
0,ndt-z5m4b_1777586035_000000000024336B,2026-05-31,ndt-z5m4b_1777586035_000000000024336B,2026-05-31 23:59:23.521835 UTC,327.928466,8.490,0.000002,Sacramento,California,95828,38.4820,-121.4015,"Comcast Cable Communications, LLC",7922,1
1,ndt-tj4lp_1777606530_000000000023459E,2026-05-31,ndt-tj4lp_1777606530_000000000023459E,2026-05-31 23:49:35.818474 UTC,2.183150,53.135,0.000000,Sacramento,California,95815,38.6096,-121.4443,Cellco Partnership DBA Verizon Wireless,6167,1
2,ndt-rdsdd_1777581688_0000000000225CFC,2026-05-31,ndt-rdsdd_1777581688_0000000000225CFC,2026-05-31 23:39:58.56144 UTC,14.749667,25.020,0.000223,Sacramento,California,95821,38.6226,-121.3885,"T-Mobile USA, Inc.",21928,1
3,ndt-hn9gw_1777604644_00000000002A5D68,2026-05-31,ndt-hn9gw_1777604644_00000000002A5D68,2026-05-31 23:29:21.878418 UTC,89.675190,14.496,0.046843,Sacramento,California,95864,38.5824,-121.3736,"Consolidated Communications, Inc.",14051,1
4,ndt-64vjq_1777563357_000000000025411F,2026-05-31,ndt-64vjq_1777563357_000000000025411F,2026-05-31 23:19:13.361482 UTC,4.369351,24.157,0.001288,Sacramento,California,95825,38.5879,-121.4053,Cellco Partnership DBA Verizon Wireless,6167,1

In [3]:
mlab.shape

(52341, 15)

In [4]:
mlab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52341 entries, 0 to 52340
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                52341 non-null  object
 1   date              52341 non-null  object
 2   test_uuid         52341 non-null  object
 3   test_time         52341 non-null  object
 4   throughput_mbps   52341 non-null  float64
 5   min_rtt_ms        52341 non-null  float64
 6   loss_rate         52341 non-null  float64
 7   client_city       52341 non-null  object
 8   client_state      52341 non-null  object
 9   postal_code       52341 non-null  int64
 10  client_latitude   52341 non-null  float64
 11  client_longitude  52341 non-null  float64
 12  isp               52265 non-null  object
 13  asn               52341 non-null  int64
 14  rn                52341 non-null  int64
dtypes: float64(5), int64(3), object(7)
memory usage: 6.0+ MB

In [5]:
# Standardize column names
mlab.columns = mlab.columns.str.lower().str.strip()
mlab.columns

Index(['id', 'date', 'test_uuid', 'test_time', 'throughput_mbps', 'min_rtt_ms',
       'loss_rate', 'client_city', 'client_state', 'postal_code',
       'client_latitude', 'client_longitude', 'isp', 'asn', 'rn'],
      dtype='object')

In [6]:
# Keep useful columns only
keep_cols = [
    "id",
    "date",
    "test_uuid",
    "test_time",
    "throughput_mbps",
    "min_rtt_ms",
    "loss_rate",
    "client_city",
    "client_state",
    "postal_code",
    "client_latitude",
    "client_longitude",
    "isp",
    "asn"
]

mlab = mlab[keep_cols].copy()
mlab.head()

,id,date,test_uuid,test_time,throughput_mbps,min_rtt_ms,loss_rate,client_city,client_state,postal_code,client_latitude,client_longitude,isp,asn
0,ndt-z5m4b_1777586035_000000000024336B,2026-05-31,ndt-z5m4b_1777586035_000000000024336B,2026-05-31 23:59:23.521835 UTC,327.928466,8.490,0.000002,Sacramento,California,95828,38.4820,-121.4015,"Comcast Cable Communications, LLC",7922
1,ndt-tj4lp_1777606530_000000000023459E,2026-05-31,ndt-tj4lp_1777606530_000000000023459E,2026-05-31 23:49:35.818474 UTC,2.183150,53.135,0.000000,Sacramento,California,95815,38.6096,-121.4443,Cellco Partnership DBA Verizon Wireless,6167
2,ndt-rdsdd_1777581688_0000000000225CFC,2026-05-31,ndt-rdsdd_1777581688_0000000000225CFC,2026-05-31 23:39:58.56144 UTC,14.749667,25.020,0.000223,Sacramento,California,95821,38.6226,-121.3885,"T-Mobile USA, Inc.",21928
3,ndt-hn9gw_1777604644_00000000002A5D68,2026-05-31,ndt-hn9gw_1777604644_00000000002A5D68,2026-05-31 23:29:21.878418 UTC,89.675190,14.496,0.046843,Sacramento,California,95864,38.5824,-121.3736,"Consolidated Communications, Inc.",14051
4,ndt-64vjq_1777563357_000000000025411F,2026-05-31,ndt-64vjq_1777563357_000000000025411F,2026-05-31 23:19:13.361482 UTC,4.369351,24.157,0.001288,Sacramento,California,95825,38.5879,-121.4053,Cellco Partnership DBA Verizon Wireless,6167

In [7]:
# Convert data types
mlab["date"] = pd.to_datetime(mlab["date"], errors="coerce")
mlab["test_time"] = pd.to_datetime(mlab["test_time"], errors="coerce")

mlab["throughput_mbps"] = pd.to_numeric(mlab["throughput_mbps"], errors="coerce")
mlab["min_rtt_ms"] = pd.to_numeric(mlab["min_rtt_ms"], errors="coerce")
mlab["loss_rate"] = pd.to_numeric(mlab["loss_rate"], errors="coerce")

mlab["client_latitude"] = pd.to_numeric(mlab["client_latitude"], errors="coerce")
mlab["client_longitude"] = pd.to_numeric(mlab["client_longitude"], errors="coerce")
mlab["asn"] = pd.to_numeric(mlab["asn"], errors="coerce")

mlab["postal_code"] = mlab["postal_code"].astype(str).str.replace(".0", "", regex=False).str.zfill(5)
mlab["client_city"] = mlab["client_city"].astype(str).str.strip()
mlab["client_state"] = mlab["client_state"].astype(str).str.strip()
mlab["isp"] = mlab["isp"].astype(str).str.strip()

mlab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52341 entries, 0 to 52340
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                52341 non-null  object
 1   date              52341 non-null  datetime64[ns]
 2   test_uuid         52341 non-null  object
 3   test_time         52341 non-null  datetime64[ns, UTC]
 4   throughput_mbps   52341 non-null  float64
 5   min_rtt_ms        52341 non-null  float64
 6   loss_rate         52341 non-null  float64
 7   client_city       52341 non-null  object
 8   client_state      52341 non-null  object
 9   postal_code       52341 non-null  object
 10  client_latitude   52341 non-null  float64
 11  client_longitude  52341 non-null  float64
 12  isp               52341 non-null  object
 13  asn               52341 non-null  int64
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), float64(5), int64(1), object(6)
memory usage: 5.6+ MB

In [8]:
# Basic filtering
before_rows = len(mlab)

mlab = mlab.dropna(subset=[
    "test_time",
    "throughput_mbps",
    "min_rtt_ms",
    "postal_code",
    "isp"
])

mlab = mlab[
    (mlab["throughput_mbps"] > 1) &
    (mlab["min_rtt_ms"].between(1, 500))
].copy()

after_rows = len(mlab)

print("Rows before cleaning:", before_rows)
print("Rows after cleaning:", after_rows)
print("Rows removed:", before_rows - after_rows)

Rows before cleaning: 52341
Rows after cleaning: 52341
Rows removed: 0

In [9]:
# Remove duplicates
before_dupes = len(mlab)

mlab = mlab.drop_duplicates().copy()

print("Duplicate rows removed:", before_dupes - len(mlab))
print("Final rows:", len(mlab))

Duplicate rows removed: 0
Final rows: 52341

In [10]:
mlab.head()

,id,date,test_uuid,test_time,throughput_mbps,min_rtt_ms,loss_rate,client_city,client_state,postal_code,client_latitude,client_longitude,isp,asn
0,ndt-z5m4b_1777586035_000000000024336B,2026-05-31,ndt-z5m4b_1777586035_000000000024336B,2026-05-31 23:59:23.521835+00:00,327.928466,8.490,0.000002,Sacramento,California,95828,38.4820,-121.4015,"Comcast Cable Communications, LLC",7922
1,ndt-tj4lp_1777606530_000000000023459E,2026-05-31,ndt-tj4lp_1777606530_000000000023459E,2026-05-31 23:49:35.818474+00:00,2.183150,53.135,0.000000,Sacramento,California,95815,38.6096,-121.4443,Cellco Partnership DBA Verizon Wireless,6167
2,ndt-rdsdd_1777581688_0000000000225CFC,2026-05-31,ndt-rdsdd_1777581688_0000000000225CFC,2026-05-31 23:39:58.561440+00:00,14.749667,25.020,0.000223,Sacramento,California,95821,38.6226,-121.3885,"T-Mobile USA, Inc.",21928
3,ndt-hn9gw_1777604644_00000000002A5D68,2026-05-31,ndt-hn9gw_1777604644_00000000002A5D68,2026-05-31 23:29:21.878418+00:00,89.675190,14.496,0.046843,Sacramento,California,95864,38.5824,-121.3736,"Consolidated Communications, Inc.",14051
4,ndt-64vjq_1777563357_000000000025411F,2026-05-31,ndt-64vjq_1777563357_000000000025411F,2026-05-31 23:19:13.361482+00:00,4.369351,24.157,0.001288,Sacramento,California,95825,38.5879,-121.4053,Cellco Partnership DBA Verizon Wireless,6167

In [11]:
from pathlib import Path

Path("data/clean").mkdir(parents=True, exist_ok=True)

mlab.to_csv("data/clean/mlab_sacramento_cleaned.csv", index=False)

print("Saved cleaned M-Lab raw-level data")

Saved cleaned M-Lab raw-level data